2024-04-08 21:21:59,172 INFO: Microblog startup [in /Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/app/__init__.py:43]
2024-04-08 21:23:27,661 INFO: Microblog startup [in /Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/app/__init__.py:43]
2024-04-08 21:23:30,232 ERROR: Exception on /edit_profile [GET] [in /Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/app/routes.py", line 97, in edit_profile
    form = EditProfileForm()
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: EditProfileForm.__init__() missing 1 required positional argument: 'original_username'
2024-04-08 21:23:34,011 ERROR: Exception on /edit_profile [GET] [in /Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/app/routes.py", line 97, in edit_profile
    form = EditProfileForm()
  File "/Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/venv/lib/python3.10/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: EditProfileForm.__init__() missing 1 required positional argument: 'original_username'
2024-04-08 21:24:34,081 INFO: Microblog startup [in /Users/anthony/workspaces/flask-mega-tutorial-2024/microblog/app/__init__.py:43]
